### ISSUE TITLE
Remove https://nawqatrends.wim.usgs.gov/NAWQATrends/

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/NAWQATrends#219]
https://nawqatrends.wim.usgs.gov/NAWQATrends/ showed up in a recent scan report - I don't believe this URL is actively being used, so please remove.

**Comment by lprivette** [comment]
This is the url for the mapper itself, which is production until v2 replaces it. I'm confused.

**Comment by HansVraga** [comment]
I thought https://nawqatrends.wim.usgs.gov/decadal/ was for the production application. @njestes Do you know if both of these links are active?
